--- 
- 
  hosts: all
  name: "to install and restart httpd service with logging"
  tasks: 
    - 
      name: "Install apache package and start it"
      yum: 
        name: httpd
        state: present
    - name: Output customized message after 600 seconds
      wait_for:
        timeout: 600
        msg: Timedout for 600 seconds

