--- 
- 
  hosts: all
  name: "to install and restart httpd service with logging"
  tasks: 
    - 
      name: "Install apache package"
      yum: 
        name: httpd
        state: present
    - 
      name: "ensure httpd is running"
      yum: 
        name: httpd
        state: started

